INSERT INTO DETALLE_BASES_POBLACIONALES ( EPS ,TIPO_DOCUMENTO ,NUM_DOCUMENTO ,APELLIDO_1 ,APELLIDO_2 ,NOMBRE_1 ["EPS"] ,FECHA_NACIMIENTO ,SEXO ,DPTO ,MPIO ,ZONA ,F_AFILIACION_EPS ,ESTADO ,F_CONTRATO ,CONTRATO ,CELULAR ,TELEFONO ,NIT_ENTIDAD ,RUTA ,PERIODO ,NOMBRE_ARCHIVO ,TIPO_CONTRATO )
     VALUES ( @EPS ,@TIPO_DOCUMENTO ,@NUM_DOCUMENTO ,@APELLIDO_1 ,@APELLIDO_2 ,@NOMBRE_1 ,@NOMBRE_2 ,@FECHA_NACIMIENTO ,@SEXO ,@DPTO ,@MPIO ,@ZONA ,@F_AFILIACION_EPS ,@ESTADO ,@F_CONTRATO ,@CONTRATO ,@CELULAR ,@TELEFONO ,@NIT_ENTIDAD ,@RUTA ,@PERIODO ,@NOMBRE_ARCHIVO ,@TIPO_CONTRATO)


            .input ("EPS", saejedj.NVarChar, item["EPS"] )
            .input ("TIPO_DOCUMENTO", saejedj.NVarChar, item["TIPO_DOCUMENTO"] )
            .input ("NUM_DOCUMENTO", saejedj.NVarChar, item["NUM_DOCUMENTO"] )
            .input ("APELLIDO_1", saejedj.NVarChar, item["APELLIDO_1"] )
            .input ("APELLIDO_2", saejedj.NVarChar, item["APELLIDO_2"] )
            .input ("NOMBRE_1", saejedj.NVarChar, item["NOMBRE_1"] )
            .input ("NOMBRE_2", saejedj.NVarChar, item["NOMBRE_2"] )
            .input ("FECHA_NACIMIENTO", saejedj.DateTime, item["FECHA_NACIMIENTO"] )
            .input ("SEXO", saejedj.NVarChar, item["SEXO"] )
            .input ("DPTO", saejedj.NVarChar, item["DPTO"] )
            .input ("MPIO", saejedj.NVarChar, item["MPIO"] )
            .input ("ZONA", saejedj.NVarChar, item["ZONA"] )
            .input ("F_AFILIACION_EPS", saejedj.DateTime, item["F_AFILIACION_EPS"] )
            .input  ("ESTADO", mssql.saejedj , item["ESTADO"] )
            .input ("F_CONTRATO", saejedj.DateTime, item["F_CONTRATO"] )
            .input ("CONTRATO", saejedj.NVarChar, item["CONTRATO"] )
            .input ("CELULAR", saejedj.NVarChar, item["CELULAR"] )
            .input ("TELEFONO", saejedj.NVarChar, item["TELEFONO"] )
            .input ("NIT_ENTIDAD", saejedj.NVarChar, item["NIT_ENTIDAD"] )
            .input ("RUTA", saejedj.NVarChar, item["RUTA"] )
            .input ("PERIODO", saejedj.NVarChar, item["PERIODO"] )
            .input ("NOMBRE_ARCHIVO", saejedj.NVarChar, item["NOMBRE_ARCHIVO"] )
            .input ("TIPO_CONTRATO", saejedj.NVarChar, item["TIPO_CONTRATO"] )